### ISSUE TITLE
Changes to project template

### ISSUE THREAD

**Issue by kayibal** [datarevenue-berlin/project-template#3]
Hey people,

let's collect here everything that we should change, fix or add in/to the project template.

**Comment by kayibal** [comment]
My suggestions:

## Deployment
* Remove overly complex deployment (reduce docker-compose files)
* Use our alpine based docker images see [dockerhub.com](https://hub.docker.com/r/drtools/)
* Remove user mapping (instead use drtools filesystem abstraction for persistence [S3|GCSFS])

## Python project
* Add structure module from rtl_reco
* Simplify default settings
* Encourage use of click cmd line interfaces which are triggered inside docker containers to run tasks.

## General
* encourage use of changelog
* add automatic CI doc building to gh pages

**Comment by kayibal** [comment]
@justuswilhelm your fixed dependencies would be nice to have here aswell.

**Comment by michcio1234** [comment]
Add one/more tmuxinator config.
I often use something like:
```
windows:
  - editor:
      layout: dd00,238x68,0,0[238x35,0,0,0,238x32,0,36{119x32,0,36,1,118x32,120,36,3}]  # three panes
      panes:
        - luigi: cd ~/qivos/deploy
        - srv: cd /srv/qivos/data
        - htop: htop
```
Which renders as:
![image](https://user-images.githubusercontent.com/16254622/33314530-364ddb64-d42e-11e7-9f5f-d8b197dad826.png)

**Comment by kayibal** [comment]
@michcio1234 Is this really project dependent? Or could you maybe template this like:
```
windows:
  - editor:
      layout: dd00,238x68,0,0[238x35,0,0,0,238x32,0,36{119x32,0,36,1,118x32,120,36,3}]  # three panes
      panes:
        - luigi: cd ~/$CURRENT_PROJECT/deploy
        - srv: cd /srv/$CURRENT_PROJECT/data
        - htop: htop
```
